/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import org.eclipse.jetty.server.Server;
import org.eclipse.jetty.servlet.ServletHandler;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new App().getGreeting());
        var server = new Server(8082);

        var handler = new ServletHandler();
        server.setHandler(handler);

        handler.addServletWithMapping(HealthServlet.class, "/health");
        handler.addServletWithMapping(MetricServlet.class, "/metric");
        server.start();
        server.join();
    }
}
